#amazonProperties:
#  endpointUrl: https://s3.ap-southeast-1.amazonaws.com
#  accessKey: ${AWS_ASSESS_KEY}
#  secretKey: ${AWS_SECRET_KEY}
#  bucketName: ${AWS_BUCKET_NAME}
#
#access:
#  key:
#    id: ${AWS_ASSESS_KEY}
#    secret: ${AWS_SECRET_KEY}
#s3:
#  region:
#    name: ap-southeast-1
#  bucket:
#    name: ${AWS_BUCKET_NAME}


# Source: https://www.twilio.com/blog/media-file-storage-java-spring-boot-amazon-s3-buckets
aws:
  bucket:
    name: ${AWS_BUCKET_NAME}
  accessKey: ${AWS_ASSESS_KEY}
  secretKey: ${AWS_BUCKET_NAME}

spring:
  profiles:
    active: ${PROFILE:local}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8082